### ISSUE TITLE
USER ID not tracking on contacts

### ISSUE THREAD

**Issue by baldrick615** [baldrick615/ContactWeb#2]
- [ ] User ID is injected,
- [ ] User ID cannot be seen or edited by Users
- [ ] Sort states alphabetically
